baseURL = "https://til.zqureshi.in"
languageCode = "en-us"
title = "Zeeshan Qureshi"
theme = "kiss"
paginate = 20
pygmentsStyle = "monokai"
pygmentsCodefences = true
enableRobotsTXT = true
googleAnalytics = "UA-38494001-1"

[params.info]
  homeTitle = "Zeeshan Qureshi - Things I've Learned"
  enableSocial = true

[params.social]
  archive = "/"
  github = "zqureshi"
  linkedin = "zeeshanq"
  profile = "https://zqureshi.in"
